export const examData = [
  {
    id: 1,
    subject: "İnformatika",
    rating: 4.5,
    duration: 30,
    questions: 26,
    title: "İnformasiyanın saxlanılması və ötürülməsi",
    tags: ["6-cı sinif", "İnformatika", "İnformasiya", "Maqistratura"],
    price: 3.0,
    isChecked: null,
  },
  {
    id: 2,
    subject: "Fizika",
    rating: 4.8,
    duration: 45,
    questions: 30,
    title: "Atomun quruluşu və elementlərin dövri cədvəli",
    tags: ["7-ci sinif", "Fizika", "Kimya"],
    price: 5.0,
    isChecked: true,
  },
  {
    id: 3,
    subject: "Biologiya",
    rating: 4.2,
    duration: 25,
    questions: 20,
    title: "Hüceyrənin tərkibi və əsas funksiyaları",
    tags: ["8-ci sinif", "Biologiya", "Təbiət"],
    price: 2.5,
    isChecked: false,
  },
  {
    id: 4,
    subject: "Ədəbiyyat",
    rating: 4.7,
    duration: 60,
    questions: 40,
    title: "Azərbaycan ədəbiyyatı tarixi",
    tags: ["9-cu sinif", "Ədəbiyyat", "Tarix"],
    price: 4.0,
    isChecked: null,
  },
];
